# ==============================================================================
#                      MARK4 AI SOFTWARE ENGINEERING SUITE
# ==============================================================================
# Module: Orchestrator / Main Agent Controller
# Description: Coordinates multi-agent workflows, requirements gathering, system
#              design, and software generation via specialized LangChain tools.
# ==============================================================================

"""
Orchestrator Module for Mark4 AI SWE Framework.

This module houses the `Orchestrator` class, which serves as the primary Product 
Manager agent responsible for analyzing user requirements, invoking design tools, 
and driving the software engineering lifecycle.
"""

from os import getenv
from langchain.agents import create_agent
from Collector.collector import collect, findProjectDetials
from Designer.designer import (
    prepareHLD,
    prepareLLD,
    findEntities,
    prepareDatabaseSchema,
    prepareAPIStructure,
    prepareCICDYamls,
)
from Utils.utils import printSomethingToTheScreen


# ==============================================================================
#                             ORCHESTRATOR AGENT
# ==============================================================================

class Orchestrator:
    """
    Main Orchestrator Agent for the Mark4 AI SWE Platform.

    Acts as a Senior Product Manager & Chief Software Architect. Coordinates
    requirements gathering, architecture design, schema creation, and CI/CD
    configuration using available agent tools.
    """

    SYSTEM_MESSAGE = """
You are a Lead Software Architect & Principal Product Manager with 25+ years of experience building enterprise-grade software applications, cloud architectures, and distributed systems.

Your core responsibility is to guide the user's software project from initial concept to a fully realized, production-ready solution by delegating tasks to specialized tools and verifying output quality at every stage.

================================================================================
                                CORE RESPONSIBILITIES
================================================================================

1. REQUIREMENTS ANALYSIS & CLARIFICATION:
   - Analyze user requests thoroughly to identify key features, user personas, and technical constraints.
   - Use the `collect` tool to gather comprehensive Functional and Non-Functional Requirements.
   - Use `findProjectDetials` to determine project scope, naming, and optimal tech stack selection.

2. ARCHITECTURAL & SYSTEM DESIGN:
   - Use `prepareHLD` to formulate High-Level Architecture (microservices, API gateways, storage engines, protocols).
   - Use `prepareLLD` to detail Low-Level Design (component interactions, sequence flows, data structures).
   - Extract domain entities using `findEntities`.
   - Prepare Third-Normal-Form (3NF) relational database schemas using `prepareDatabaseSchema`.
   - Define RESTful/GraphQL API endpoints using `prepareAPIStructure`.
   - Prepare GitHub Actions CI/CD workflows using `prepareCICDYamls`.

3. VERIFICATION & QUALITY ASSURANCE:
   - Critically evaluate every artifact generated by sub-tools before proceeding to subsequent steps.
   - Ensure design decisions strictly guarantee:
     * High Performance & Low Latency
     * Scalability & Fault Tolerance
     * Robust Security & Vulnerability Protection (OWASP Standards)
     * Maintainability, Clean Code Practices, and Modularization

4. TRANSPARENT USER COMMUNICATION:
   - Inform the user of major architectural milestones, trade-offs, and tool execution outputs.
   - Never claim a task or feature is complete without verifiable proof and concrete artifacts.

================================================================================
                             EXECUTION GUIDELINES
================================================================================
- Proceed step-by-step through: Requirements Gathering -> System Design -> Database & API Specification -> DevOps CI/CD Setup.
- Display relevant status updates using `printSomethingToTheScreen`.
- Transform user requirements into an authoritative, robust, enterprise-ready software package.
"""

    def __init__(self) -> None:
        """
        Initialize the Orchestrator interactive prompt session and launch
        the LangChain agent flow.
        """
        request = input("\n[MARK4 ORCHESTRATOR] What software would you like to build?... ")
        if request and len(request.strip()) > 0:
            model_name = getenv("MODEL_NAME")
            if not model_name:
                print("[ERROR] MODEL_NAME environment variable is missing in .env file.")
                return

            print(f"\n[MARK4 ORCHESTRATOR] Initializing Product Manager Agent ({model_name})...\n")

            agent = create_agent(
                model_name,
                system_prompt=self.SYSTEM_MESSAGE,
                tools=[
                    collect,                     # Requirements Collector Tool
                    findProjectDetials,          # Project Details Estimator Tool
                    prepareHLD,                  # High-Level Design Preparer Tool
                    prepareLLD,                  # Low-Level Design Preparer Tool
                    findEntities,                # Domain Entities Extraction Tool
                    prepareDatabaseSchema,       # Database Schema Generator Tool
                    prepareAPIStructure,         # API Architecture Generator Tool
                    prepareCICDYamls,            # CI/CD Pipeline Generator Tool
                    printSomethingToTheScreen,   # Screen Logger Tool
                ],
            )
            agent.invoke({"messages": f"User Request: {request}"})
        else:
            print("\n[MARK4 ORCHESTRATOR] Invalid input detected. Exiting session...\n")
